version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'twrp-6.0'
      VERSION: '2.9.1'
      PBRP_BRANCH: 'features'
      VENDOR: 'LYF'
      CODENAME: 'panda01a'
      BUILD_LUNCH: 'omni_panda01a-eng'
      TEST_BUILD: 'true'
    working_directory: /home/builder/pitchblack
    steps:
      - checkout
      - run:
          name: AIO Build
          command: |
            sudo apt-get install -y tar
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            export TEST_BUILD=true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            sed -i "s:GITHUB_TOKEN@github.com\/PitchBlackRecoveryProject:GITHUB_TOKEN@github.com\/AndroiableDroid:" build.sh
            source build.sh ${SFUserName} ${SFPassword} ${GITHUB_TOKEN}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: "android-6.0"
          context: upload
